#项目相关配置
ruoyiBackup:
  # 名称
  name: ruoyiBackup
  # 版本
  version: 3.3.0
  # 版本年份
  copyrightYear: 2019
  # 文件路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat的最大线程数，默认值200
    max-threads: 800
    # tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
## Shiro
#shiro:
#  user:
#    # 登录地址
#    loginUrl: /login
#    # 权限认证失败地址
#    unauthorizedUrl: /unauth
#    # 首页地址
#    indexUrl: /index
#    # 验证码开关
#    captchaEnabled: true
#    #验证码类型 math 数组计算 char 字符
#    captchaType: math
#  cookie:
#    # 设置Cookie的域名 默认空，即当前访问的域名
#    domain:
#    # 设置Cookie的有效访问路径
#    path: /
#    # 设置HttpOnly属性
#    httpOnly: true
#    # 设置Cookie的过期时间，天为单位
#    maxAge: 30
#  session:
#    # Session超时时间（默认30分钟）
#    expireTime: 30
#    # 同步session到数据库的周期（默认1分钟）
#    dbSyncPeriod: 1
#    # 相隔多久检查一次session的有效性，默认就是10分钟
#    validationInteval: 10